# Generated by Django 4.2 on 2023-06-30 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$')])),
                ('address', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('fees', models.FloatField()),
            ],
        ),
    ]
